### ISSUE TITLE
Does not like matrix for `runs-on`

### ISSUE THREAD

**Issue by janpio** [cschleiden/vscode-github-actions#100]
I have quite a few jobs with a matrix that defines the `runs-on`:
```

... 

  process-managers:
    needs: start-time

    strategy:
      fail-fast: false
      matrix:
        engine: ['napi', 'binary']
        feature: [pm2]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

...

```

The `${{ matrix.os }}` is marked as an error:

![image](https://user-images.githubusercontent.com/183673/121421455-7915f600-c96e-11eb-8ab0-869acafe55e7.png)

But this works just fine in practice.

Via https://github.com/prisma/e2e-tests/blob/dev/.github/workflows/test.yaml
