### ISSUE TITLE
Some secrets are marked as "Unknown access context"

### ISSUE THREAD

**Issue by janpio** [cschleiden/vscode-github-actions#101]
Job with a secret as an env var:

```
  process-managers:
    needs: start-time
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
...

```

is shown as 

![image](https://user-images.githubusercontent.com/183673/121421741-c72af980-c96e-11eb-8174-3ace3e98b2ab.png)

But: https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow
And it also works just fine.

Via https://github.com/prisma/e2e-tests/blob/dev/.github/workflows/test.yaml

**Comment by janpio** [comment]
Somehow does not apply to all secrets:

![image](https://user-images.githubusercontent.com/183673/121421877-eb86d600-c96e-11eb-9b21-43212b004132.png)

**Comment by jacob-beltran** [comment]
FWIW the weird commonality here is that the error only seems to happen with secrets that begin with `S`. Very strange indeed.
<img width="477" alt="2021-09-09 _16 28 08__LKzDfQaV@2x" src="https://user-images.githubusercontent.com/1900200/132775404-6be22cab-4d3a-4d4e-8e93-796b9505a4dc.png">

**Comment by jkoenig134** [comment]
> FWIW the weird commonality here is that the error only seems to happen with secrets that begin with `S`. Very strange indeed.
> <img alt="2021-09-09 _16 28 08__LKzDfQaV@2x" width="477" src="https://user-images.githubusercontent.com/1900200/132775404-6be22cab-4d3a-4d4e-8e93-796b9505a4dc.png">

I also get this error with secrets starting with other letters.

**Comment by parkeyparker** [comment]
I've been having this issue with Organisation level secrets but not repo level secrets so I guess that may be the commonality... I have only just found the setting to enable org features but that doesn't seem to have resolved it - for the org in question I am not an admin so perhaps my user can't even check that a secret exists?

**Comment by ybulakhau** [comment]
I have the same problem, is there any solution? Enabling org features didn't help.

**Comment by neongreen** [comment]
I get this for secrets used inside `run:` clauses.

This is fine:

```yaml
      - name: Checkout the dumps repo
        uses: actions/checkout@v2
        with:
          repository: brickdo/dumps
          ssh-key: ${{ secrets.DUMPS_DEPLOY_KEY }}
```

This isn't:

```yaml
      - name: test
        run: |
          echo ${{ secrets.DUMPS_DEPLOY_KEY }}
```

**Comment by danburonline** [comment]
Has anyone figured out how to get rid of these errors? I was working on a GitHub Action and suddenly these errors appeared:
<img width="100%" alt="image" src="https://user-images.githubusercontent.com/34251194/192232350-79a9ea23-9c23-476b-bbfd-f071c79bb572.png">

The strange thing is that a few lines above these errors, I use the same env var in exactly the same way, and there are no errors... This is strange behaviour.
<img width="100%" alt="image" src="https://user-images.githubusercontent.com/34251194/192232485-117b7273-ecc6-42c6-a5ab-8c3f605e5263.png">

**Comment by pixare40** [comment]
seems to be happening with organisational repo secrets

**Comment by cschleiden** [comment]
@danburonline could you share more of that workflow (job)? Feel free to remove any steps in between but would be good to see the two `uses` steps with context.

**Comment by einarpersson** [comment]
I get this error for env variables which are defined in one step and then used in another step through appending to `$GITHUB_ENV`

````yml
      - name: Main version
        run: |
          cd main
          MAIN_VERSION=$(npm exec -c 'node -e "console.log(process.env.npm_package_version)"')
          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
          cd ..

      - name: Branch version
        run: |
          cd branch
          BRANCH_VERSION=$(npm exec -c 'node -e "console.log(process.env.npm_package_version)"')
          echo "BRANCH_VERSION=$BRANCH_VERSION" >> $GITHUB_ENV
          cd ..

      - run: |
          echo "Main: ${{ env.MAIN_VERSION }}\nBranch: ${{ env.BRANCH_VERSION }}"

      - name: Fail if version is not bumped
        run: if [ ${{ env.MAIN_VERSION }} == ${{ env.BRANCH_VERSION }} ]; then exit 1; else exit 0; fi
````

**Comment by cschleiden** [comment]
@einarpersson That's currently not supported, created a new enhancement issue here: https://github.com/cschleiden/vscode-github-actions/issues/200

**Comment by danburonline** [comment]
@cschleiden Sure! Here is the entire snippet of where the errors appear:

```yaml
- name: "Terragrunt init"
  uses: the-commons-project/terragrunt-github-actions@master
  with:
    tf_actions_version: ${{ env.tf_version }}
    tg_actions_version: ${{ env.tg_version }}
    tf_actions_subcommand: "init -upgrade"
    tf_actions_working_dir: ${{ env.WORKING_DIR }}
    tf_actions_comment: true
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    AWS_ACCESS_KEY_ID: ${{ secrets[env.AWS_ACCESS_KEY_ID_VAR] }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_VAR] }}

- name: "Terragrunt validate"
  uses: the-commons-project/terragrunt-github-actions@master
  with:
    tf_actions_version: ${{ env.tf_version }}
    tg_actions_version: ${{ env.tg_version }}
    tf_actions_binary: "terraform"
    tf_actions_subcommand: "validate"
    tf_actions_working_dir: ${{ env.WORKING_DIR }}
    tf_actions_comment: true
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    AWS_ACCESS_KEY_ID: ${{ secrets[env.AWS_ACCESS_KEY_ID_VAR] }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_VAR] }}
```

They do not, however some lines above at this step:

```yaml
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws-access-key-id: ${{ secrets[env.AWS_ACCESS_KEY_ID_VAR] }}
    aws-secret-access-key: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_VAR] }}
    aws-region: eu-central-1
```

I hope this gives you some more information.
