### ISSUE TITLE
[BUG] using matrix

### ISSUE THREAD

**Issue by MrNossiom** [cschleiden/vscode-github-actions#104]
Hello, when using matrix.os, the extension resolve it to true.

```yml
name: Node.js CI

on: [push, pull_request]

jobs:
    test:
        strategy:
            fail-fast: true
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
                    - macos-latest
        name: Test on Node.js v16 on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        env:
            TOKEN: ${{ secrets.DISCORD_TEST_TOKEN }}
            DATABASE_URL: postgresql://MeTomT:aSecretPassword@localhost/MeTomT
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
```

I have this error: `'true' is not in the list of allowed values`

```json
{
	"resource": "/path/to/project/folder/.github/workflows/main.yml",
	"owner": "github-actions",
	"severity": 8,
	"message": "'true' is not in the list of allowed values",
	"startLineNumber": 15,
	"startColumn": 18,
	"endLineNumber": 15,
	"endColumn": 34
}
```

Is it a problem from my configuration, or is there a bug ?

Thanks for any answers
MrNossiom
