### ISSUE TITLE
"Could not retrieve values: Not found"

### ISSUE THREAD

**Issue by janpio** [cschleiden/vscode-github-actions#123]
![image](https://user-images.githubusercontent.com/183673/132423849-757d41fe-0505-4273-9a36-66fb8e757313.png)

```
      - name: Trigger e2e tests for Insider
        if: ${{ steps.check_published_version.outputs.new_insider_version }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: E2E tests after release on VSIX
          token: ${{ secrets.GH_TOKEN }}
          inputs: '{ "extension_type": "insider", "extension_version": "${{ steps.check_published_version.outputs.new_insider_version }}" }'
```

Seems to happen on the `with` values of external actions.

**Comment by cschleiden** [comment]
This seems to be because the action uses `action.yaml` and the extension is looking for `action.yml`. There is fallback code that should look for either file, but apparently that's not working in this case.

**Comment by FrostyLeaf** [comment]
The extension also fails on actions that are defined in subdirectories. for example:

```yaml
    - name: Automated CD
      if: steps.setup-vars.outputs.deploy
      uses: <Org>/actions/.github/actions/applications-register-action@master
      with:
        githubToken: '${{ secrets.GH_CD_TOKEN }}'
        namespace: ${{ github.event.inputs.namespace || 'dev' }}
        appYaml: '.helm/app.yaml'
```

![image](https://user-images.githubusercontent.com/8349568/148491088-481e1184-43d5-4d07-96bc-1169536ed8f6.png)

**Comment by FrostyLeaf** [comment]
Is there anyway to suppress these problems before it get fixed?

**Comment by baptisteArno** [comment]
Same issue with:

```yaml
- name: Delete Storybook Serverless Container Scaleway
        uses: philibea/scaleway-containers-deploy@v1.0.8
        with:
          type: 'teardown'
          scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          scw_dns: ${{ secrets.SCW_DNS }}
          scw_containers_namespace_id: ${{ secrets.SCW_CONTAINERS_NAMESPACE_ID }}
          scw_registry: ${{ env.IMAGE_NAME }}:${{ env.STORYBOOK_BRANCH_SLUG }}
```

Would be nice to at least suppress the error?
