### ISSUE TITLE
Marks input parameter as missing if `required: true` but provided with `default` value

### ISSUE THREAD

**Issue by JamesMGreene** [cschleiden/vscode-github-actions#132]
Given the following YAML in my workflow:

```yaml
      - name: Gather files changed
        uses: trilom/file-changes-action@a6ca26c14274c33b15e6499323aac178af06ad4b
        id: get_diff_files
        with:
          # So that `steps.get_diff_files.outputs.files` becomes
          # a string like `foo.js path/bar.md`
          output: ' '
```

I am receiving the following linter error messages:

![image](https://user-images.githubusercontent.com/417751/145935594-c7ba9b3a-114c-4cd2-a132-30660c76bd41.png)

Diving into the corresponding custom action's `action.yml` metadata file, it looks like these two input parameters are defined as `required: true` but _also_ provided with `default` values, such that I as a consumer do not need to explicitly provide values for them.

https://github.com/trilom/file-changes-action/blob/a6ca26c14274c33b15e6499323aac178af06ad4b/action.yml#L8-L11

```yaml
  githubToken:
    description: 'The github action token will be used by default, if you want to use something different than you can pass it in here.'
    default: ${{ github.token }}
    required: true
```

https://github.com/trilom/file-changes-action/blob/a6ca26c14274c33b15e6499323aac178af06ad4b/action.yml#L25-L28

```yaml
  fileOutput:
    description: 'Choose between json (default), or custom delimiter by passing a string, for example '','' for csv file output.  If you set as json the file output will be suffixed with .json, if you select '','' then the output will be .csv, else .txt will be the output.'
    required: true
    default: json
```

This seems to be a reasonable configuration to me, so I suspect this parser/linter needs to be updated to recognize this kind of configuration combination. 🤔
