### ISSUE TITLE
Workflows using reusable workflows are reported as incorrect

### ISSUE THREAD

**Issue by whi-tw** [cschleiden/vscode-github-actions#162]
The following workflow:

```yaml
---
name: Lint Code Base

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/reusable-superlinter.yml
```

Shows some errors:

* 'lint': `Missing required key 'runs-on'` and `Missing required key 'steps'`
* 'uses': `Key 'uses' is not allowed`

These are both incorrect in this case: https://docs.github.com/en/actions/using-workflows/reusing-workflows
