### ISSUE TITLE
Support emojis in description of action file

### ISSUE THREAD

**Issue by MichaelCurrin** [cschleiden/vscode-github-actions#53]
Hi, I am using a popular GH Actions action which builds a site to GH Pages.

I noticed that this extension gives me errors in VS Code when it tries to parse an emoji in an action.

![null](https://user-images.githubusercontent.com/18750745/99277643-b8e08900-2836-11eb-92f8-ba08f40e3cd0.png)

Here is the offending line - a description of `action.yml` which includes an emoji.

https://github.com/MichaelCurrin/actions-gh-pages/blob/main/action.yml#L2

```yaml
description: 'GitHub Actions for GitHub Pages 🚀 Deploy...
```

**Comment by MichaelCurrin** [comment]
Here is my code, if you want to paste it in a local config file. You don't need anything specific to my project to check the error.

 ```yaml
jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Deploy to GH Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        # feature branch without emoji - works fine
        uses: MichaelCurrin/actions-gh-pages@description-remove-emoji
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build

      - name: Deploy to GH Pages 🚀
        if: ${{ github.event_name != 'pull_request' }}
        # main branch with emoji - causes warning fine
        uses: MichaelCurrin/actions-gh-pages@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
```
