### ISSUE TITLE
Unknown context access for workflow_dispatch inputs and step outputs

### ISSUE THREAD

**Issue by Cyberbeni** [cschleiden/vscode-github-actions#61]
https://github.com/Cyberbeni/install-swift-tool/blob/master/.github/workflows/update-dependencies.yml
Both lines with `if: ...` say unknown context access
```yaml
name: "Update dependencies"

on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Also create pull request if only developer dependencies changed'
        default: 'false'
  schedule:
    - cron: '37 4 * * 6'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update dependencies
      run: yarn upgrade --latest
    - name: Build
      run: make
    - name: Detect changes in distributed code
      if: ${{ github.event.inputs.force != 'true' }}
      id: changes
      run: |
        if [[ $(git status --porcelain ./dist) != "" ]]; then
          echo "::set-output name=dist::true"
        fi
    - name: Create Pull Request
      if: ${{ steps.changes.outputs.dist || github.event.inputs.force == 'true' }}
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update dependencies"
        branch: yarn-upgrade-latest
        delete-branch: true
        title: "Update dependencies"
        body: "Automatically created by the 'Update Dependencies' workflow"

```
