### ISSUE TITLE
Accept all matrix expressions for dynamic matrix strategies

### ISSUE THREAD

**Issue by cschleiden** [cschleiden/vscode-github-actions#64]
For a dynamic matrix, like in https://github.com/cschleiden/vscode-github-actions/issues/55, the parser cannot determine the valid matrix keys. Therefore all matrix accesses should be marked valid

```yaml
strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.metadata.outputs.webpack-matrix) }} # Once the parser sees an expression here, all accesses should be marked as valid
    steps:
      # ..
      - name: Test integration
        env:
          MATRIX_WEBPACK_VERSION: ${{ matrix.webpack }} # this fails currently
        run: npm run test-integration-webpack
```
