### ISSUE TITLE
[PROPOSE] Add `!` snippet like in Emmet

### ISSUE THREAD

**Issue by talk2much** [cschleiden/vscode-github-actions#73]
Add template for fast bootstrapping actions with most popular fields.

My example for just created `build-package.yml` workflow:

```
! (tab)
```
Would give
```yml
name: ${0:Build Package} # Sorry can't figure out regex for sentence case
on:
  push:
    branches: [${1:default branch}]
jobs:
  ${2:$TM_FILENAME_BASE}:
    runs-on: ubuntu-latest
    steps:
      - $3
```
