### ISSUE TITLE
Doesn't know top level `defaults`

### ISSUE THREAD

**Issue by janpio** [cschleiden/vscode-github-actions#99]
```
name: test

on:
  push:

defaults:
  run:
    # this makes windows use bash as well, which makes `...  >> $GITHUB_ENV` work there
    shell: bash
    
 ...
```

is shown as

![image](https://user-images.githubusercontent.com/183673/121421182-2b998900-c96e-11eb-8339-a9e29f706ffa.png)

But this exists and works: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaults

Via https://github.com/prisma/e2e-tests/blob/dev/.github/workflows/test.yaml
